### PR TITLE
switch to hcdev test

### PR DESCRIPTION
**Pull request by Connoropolous**
. docker/run-ci  passes successfully, given that `hcdev test` is merged in holochain-cmd now

### CODE REVIEW

**Comment by Connoropolous** [comment]
@lucksus well the tweak to the holoconsole itself has to go into holochain-cmd, unfortunately. 

Also, I don't have any edit rights here so go ahead and merge if you want.

**Comment by zippy** [comment]
Hey @Connoropolous I've updated your access rights.

**Comment by lucksus** [comment]
This PR is merging from your own repo, @Connoropolous, right?

**Comment by Connoropolous** [comment]
K, I will update Readme. And yeah, PR was opened from a fork I created since I couldn't push a branch to here yet

**Pull request merged**
