### PR TITLE
genesis macro

### PR DESCRIPTION
**Pull request by Connoropolous**
The proposed dev camp spec
https://github.com/holochain/hdk-rust/projects/1?fullscreen=true

https://github.com/holochain/hdk-rust/issues/21

### CODE REVIEW

**Comment by ddd-mtl** [comment]
How about `zome_callback!(genesis)` ?

Since we have `zome_functions!` already.
and possibly `zome_entry_types!`

**Comment by Connoropolous** [comment]
That kinda makes sense, because eventually there would be `zome_callbacks(receive)` too

**Comment by Connoropolous** [comment]
@ddd-mtl I am going to update to your suggestion

**Comment by Connoropolous** [comment]
But is it `zome_callback!(genesis)` or `zome_callback(genesis)!` ?

**Comment by willemolding** [comment]
Following the syntax for validation as closely as possible how about the macro

```
zome_callback!(genesis)  {
    // do logic to check if genesis should pass
    Ok(())
   // or
   Err("User does not meet requirements to join")
}
```

which should produce: 
 
```
pub extern "C" fn genesis(encoded_allocation_of_input: u32) -> u32 {
    fn execute() -> Result<(), String> {
        $main_block
    }

    let result = execute();

    match result {
        Ok(()) => 0,
        Err(fail_string) => ::hdk::serialize_wasm_output(fail_string),
    }
}
```

**Comment by Connoropolous** [comment]
Looks spot on to my eyes Willem

**Pull request closed without merging**
